Disable sendfile for gunicorn
* fixes this error with lock-passwordless (which is the largest JS file)

```
   ...
   File "/usr/local/lib/python3.4/site-packages/gunicorn/http/wsgi.py", line 386, in sendfile
     sent += os.sendfile(sockno, fileno, offset + sent, count)
 BlockingIOError: [Errno 11] Resource temporarily unavailable
```